twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        admin_skin: 'skin-dark'
        layout_option: 'sidebar-mini'
        menuBuilder: "@app.menu_builder"
        baseUrl: '%env(BASE_URL)%'
        capi_client_id: '%env(CAPI_CLIENT_ID)%'

