controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: '' # don't prefix URLs for English, the default locale
        he: '/he'
        es: '/es'
        fr: '/fr'
        ru: '/ru'
        de: '/de'
        pt: '/pt'
        nl: '/nl'