user:
    1:
        header: "Squadron"
    2:
        item: "Announcements"
        route: "show_announcements"
        icon: "fa fa-bullhorn"
    3:
        item: "Squadron Dashboard"
        route: "dashboard"
        icon: "fa fa-chart-area"
    4:
        item: "Squadron Leaderboard"
        route: "leaderboard"
        icon: "ed-asset ed-asset-icon-leaderboard_website margin-r-5"
        star: false
#    5:
#        item: "Squadron Activities"
#        icon: "fa fa-line-chart"
    6:
        item: "Squadron Roster"
        route: "app_members"
        icon: "fa fa-user-astronaut"
        star: false
    7:
        header: "Player"
    8:
        item: "Player Activities Report"
        route: "app_player_reports"
        icon: "fa fa-chart-line"
        star: true
    9:
        item: "Player Journal Log"
        route: "app_import"
        icon: "fa fa-upload"
    10:
        item: "My Profile"
        route: "app_profile"
        icon: "fa fa-cog"
admin:
    1:
        item: "Squadron Settings"
        route: "admin_squadron_settings"
        icon: "fa fa-tools"
        roles: ["ROLE_ADMIN"]
    2:
        item: "Manage Announcements"
        route: "admin_list_announcements"
        routes: ["admin_list_announcements", "admin_announcements_edit", "admin_announcements_new"]
        icon: "fa fa-bullhorn"
        roles: ["ROLE_ADMIN","ROLE_EDITOR"]
    3:
        item: "Manage Members"
        route: "admin_list_members"
        routes: ["admin_list_members","admin_edit_member"]
        icon: "ed-asset-icon-members margin-r-5"
        roles: ["ROLE_ADMIN","CAN_EDIT_USER","CAN_CHANGE_STATUS","CAN_EDIT_PERMISSIONS","CAN_VIEW_HISTORY"]
    4:
        item: "MOTD"
        route: "admin_list_motd"
        routes: ["admin_list_motd","admin_motd_new","admin_motd_edit"]
        icon: "fa fa-exclamation-triangle"
        roles: ["ROLE_SUPERUSER"]