user:
    1:
        header: "Squadron"
    2:
        item: "Announcements"
        route: "show_announcements"
        icon: "fa fa-bullhorn"
        counter: true
        counter_sql: "select a.counter + b.counter as counter from (select 1 as id, count(a.id) as counter from announcement a left join user u on a.squadron_id=u.squadron_id left join read_history rh on rh.announcement_id=a.id and rh.user_id=u.id where u.id=:user and a.published_flag=1 and a.publish_at < now() and rh.id is null) a, (select 1 as id, count(m.id) as counter from motd m left join read_history rh on rh.motd_id=m.id and rh.user_id=:user where m.show_flag=1 and rh.id is null) b where a.id=b.id;"
        counter_color: "red"
        counter_title: "Unread Messages"
    3:
        item: "Squadron Dashboard"
        route: "dashboard"
        icon: "fa fa-chart-area"
    4:
        item: "Squadron Leaderboard"
        route: "leaderboard"
        icon: "ed-asset ed-asset-icon-leaderboard_website margin-r-5"
#    5:
#        item: "Squadron Activities"
#        icon: "fa fa-line-chart"
    6:
        item: "Squadron Roster"
        route: "app_members"
        icon: "fa fa-user-astronaut"
    7:
        header: "Player"
    8:
        item: "Player Dashboard"
        route: "player_dashboard"
        icon: "fa fa-chart-area"
    9:
        item: "Player Activities Report"
        route: "app_player_reports"
        icon: "fa fa-chart-line"
    10:
        item: "My Achievements"
        route: "achievement"
        icon: "fa fa-trophy"
        counter: true
        counter_sql: "select count(id) from achievement where user_id=:user"
        counter_color: "green"
        counter_title: "New Trophies"
    11:
        item: "Player Journal Log"
        route: "app_import"
        icon: "fa fa-upload"
        alert: true
        alert_sql: "select refresh_failed as alert from oauth2 where user_id=:user"
        alert_color: "red"
        alert_icon: "fas fa-exclamation"
    12:
        item: "My Profile"
        route: "app_profile"
        icon: "fa fa-cog"
    13:
        header: "Management"
        roles: ["ROLE_ADMIN", "CAN_VIEW_REPORTS"]
    #    14:
    #        item: "Criminal History"
    #        route: ""
    #        icon: "fa fa-shield-alt"
    #        roles: ["ROLE_ADMIN", "CAN_VIEW_REPORTS"]
    15:
        item: "Commander Performance"
        route: "to-do"
        icon: "fa fa-tachometer-alt"
        roles: ["ROLE_ADMIN", "CAN_VIEW_REPORTS"]
    16:
        item: "Commander Activities"
        route: "mgr_reports"
        icon: "fa fa-fighter-jet"
        star: true
        roles: ["ROLE_ADMIN", "CAN_VIEW_REPORTS"]
    17:
        item: "Promotion Voting"
        route: "to-do"
        icon: "fa fa-check-square"
        roles: ["ROLE_ADMIN", "CAN_VIEW_REPORTS"]
admin:
    1:
        item: "Squadron Settings"
        route: "admin_squadron_settings"
        icon: "fa fa-tools"
        star: true
        roles: ["ROLE_ADMIN"]
    2:
        item: "Manage Announcements"
        route: "admin_list_announcements"
        routes: ["admin_list_announcements", "admin_announcements_edit", "admin_announcements_new"]
        icon: "fa fa-bullhorn"
        roles: ["ROLE_ADMIN","ROLE_EDITOR"]
    3:
        item: "Manage Members"
        route: "admin_list_members"
        routes: ["admin_list_members","admin_edit_member"]
        icon: "ed-asset-icon-members margin-r-5"
        counter: true
        counter_sql: "select count(u.id) as counter from user u where u.squadron_id in (select squadron_id from user where id=:user) and u.status_id=1"
        counter_color: "orange"
        counter_title: "Pending Members"
        roles: ["ROLE_ADMIN","CAN_EDIT_USER","CAN_CHANGE_STATUS","CAN_EDIT_PERMISSIONS","CAN_VIEW_HISTORY"]
    4:
        item: "Manage Achievements"
        route: "to-do"
        icon: "fa fa-trophy"
        roles: ["ROLE_ADMIN"]
    5:
        item: "MOTD"
        route: "admin_list_motd"
        routes: ["admin_list_motd","admin_motd_new","admin_motd_edit"]
        icon: "fa fa-exclamation-triangle"
        roles: ["ROLE_SUPERUSER"]